config-version: 1.3
debug:
  messages: false
  timings: false
language: EN-US
discord:
  use: false
  OAuth: ""
api:
  format-console-messages: false
  legendchat-tags: []
mention:
  enable: true
  color-template: '&e@{mentioned-player}{group-suffix}'
  playsound: note_pling
  hover-message: '&e{playername} mentioned you!'
general:
  URL-template: 'Click to open &n{url}&r'
  console-tag: '&6 {console}&3'
  remove-from-chat:
  - '[]' 
  - '&7[]'
  - '&7[&7]'
  remove-unnused-placeholderapi: true
  channel-cmd-aliases: channel,ch
  umsg-cmd-aliases: umsg, pv
  json-events: true
  default-channel: g
  spy-format: '&c&o[Spy] {output}'
  use-channel-tag-builder: true
  default-tag-builder: world,marry-tag,ch-tags,clan-tag,factions,group-prefix,nickname,group-suffix,message
  enable-tags-on-messages: false
  item-hand:
    enable: true
    format: '&6[hand]{group-suffix}'
    placeholder: '@hand'
tell:
  cmd-aliases: tell,t,w,m,msg,private,priv,r
  prefix: '&6[&c{playername} &6-> &c{receivername}&6]: '
  format: '{message}'
  hover-messages: []
bungee:
  prefix: '&6[&c{playername} &6-> &c{receivername}&6]: '
  format: '{message}'
  hover-messages: []
broadcast:
  enable: true
  on-hover: 'hover:'
  on-click: 'click:' 
  suggest: 'suggest:'  
  url: 'url:'
  aliases: ubroad,uannounce,usay,uaction,all,anunciar,todos
tags:
  group-prefix:
    format: '&7[{group-prefix}&7]&r'
    click-cmd: ''
    suggest-cmd: ''
    hover-messages: 
    - '&bRank: &e{prim-group}'
    permission: ''
    show-in-worlds: []
    hide-in-worlds: []
  playername:
    format: '{playername}'
    click-cmd: 'tpa {playername}'
    suggest-cmd: ''
    hover-messages: 
    - '&7Click to send teleport request'
    permission: ''
    show-in-worlds: []
  nickname:
    format: '{nickname}'
    click-cmd: ''
    suggest-cmd: ''
    hover-messages:
    - '&6Realname: {playername}'
    permission: ''
    show-in-worlds: []
    hide-in-worlds: []
  group-suffix:
    format: '&r{group-suffix}: '
    click-cmd: ''
    suggest-cmd: ''
    hover-messages: []
    permission: ''
    show-in-worlds: []
    hide-in-worlds: []
  world:
    format: '&7[{world}]&r'
    click-cmd: ''
    suggest-cmd: ''
    hover-messages:
    - '&7Sent from world {world}'
    permission: ''
    show-in-worlds: []
  message:
    format: '{message}'
    click-cmd: ''
    suggest-cmd: ''
    hover-messages: []
    show-in-worlds: []
    hide-in-worlds: []
  ch-tags:
    format: '{ch-color}[{ch-alias}]&r'
    click-cmd: 'ch {ch-alias}'
    suggest-cmd: ''
    hover-messages:
    - '&3Channel name: {ch-color}{ch-name}'
    - '&bClick to go to this channel!'
    permission: ''
    show-in-worlds: []
    hide-in-worlds: []
  clan-tag:
    format: '{clan-ctag}'
    click-cmd: 'clan search {playername}'
    suggest-cmd: ''
    hover-messages:
    - '&bClan Tag: &7{clan-tag}'
    - '&bClan Name: &7{clan-name}'
    - '&bClan KDR: &7{clan-totalkdr}'
    - '&bPlayer KDR: &7{clan-kdr}'
    - '&bPlayer Rank: &7{clan-rank}'
    - '&bIs Leader: &7{clan-isleader}'
    - '&3Click for more info about this player'
    permission: ''
    show-in-worlds: []
    hide-in-worlds: []
  marry-tag:
    format: '{marry-prefix}{marry-suffix}'
    click-cmd: ''
    suggest-cmd: ''
    hover-messages: 
    - '&cMarried with {marry-partner}'
    permission: ''
    show-in-worlds: []
    hide-in-worlds: []
  admin-chat:
    format: '&b[&r{playername}&b] '
    click-cmd: ''
    suggest-cmd: ''
    hover-messages: []
    permission: ''
    show-in-worlds: []
    hide-in-worlds: []
  bungee:
    format: '&7[{world}]{ch-color}[Bungee-{server}] {playername}: &7'
    click-cmd: ''
    suggest-cmd: ''
    hover-messages:
    - '{ch-color}Sent from server -{server}-'
    permission: ''
    show-in-worlds: []
    hide-in-worlds: []
  custom-tag:
    format: '&7[&2MyTag&7]&r'
    click-cmd: ''
    suggest-cmd: ''
    hover-messages: []
    permission: 'any-name-perm.custom-tag'
    show-in-worlds: []
    hide-in-worlds: []
  factions:
    format: '&7[{fac-relation-color}{fac-relation-name}&7]&r'
    click-cmd: ''
    suggest-cmd: ''
    hover-messages: 
    - '&7Faction name: {fac-relation-color}{fac-name}'
    - '&7Motd: &a{fac-motd}'
    - '&7Description: {fac-description}'
    permission: ''
    show-in-worlds: []
    hide-in-worlds: []